Katie Briggs
Week 8  Exercise 11.3.2 from the Mining of Massive Dataset text
DSC550-302

In [1]:
# import required libraries
import pandas as pd
import numpy as np
from scipy.linalg import svd

In [3]:

movie_main = np.array([[1,1,1,0,0],[3,3,3,0,0],[4,4,4,0,0],[5,5,5,0,0],[0,0,0,4,4],[0,0,0,5,5],[0,0,0,2,2]])
movie_main

array([[1, 1, 1, 0, 0],
       [3, 3, 3, 0, 0],
       [4, 4, 4, 0, 0],
       [5, 5, 5, 0, 0],
       [0, 0, 0, 4, 4],
       [0, 0, 0, 5, 5],
       [0, 0, 0, 2, 2]])

In [4]:

# add Leslie's 
movie_leslie = np.array([[1,1,1,0,0],[3,3,3,0,0],[4,4,4,0,0],
                   [5,5,5,0,0],[0,0,0,4,4],[0,0,0,5,5],
                   [0,0,0,2,2],[0,3,0,0,4]])

movie_leslie

array([[1, 1, 1, 0, 0],
       [3, 3, 3, 0, 0],
       [4, 4, 4, 0, 0],
       [5, 5, 5, 0, 0],
       [0, 0, 0, 4, 4],
       [0, 0, 0, 5, 5],
       [0, 0, 0, 2, 2],
       [0, 3, 0, 0, 4]])

In [5]:
# create SVD
L_U, L_s, L_VT = svd(movie_leslie)
Uo, so, VTo = svd(movie_main)

Leslie = np.array([0,3,0,0,4])
VTo

array([[-0.57735027, -0.57735027, -0.57735027,  0.        ,  0.        ],
       [-0.        , -0.        , -0.        , -0.70710678, -0.70710678],
       [-0.81649658,  0.40824829,  0.40824829, -0.        , -0.        ],
       [ 0.        ,  0.        ,  0.        , -0.70710678,  0.70710678],
       [ 0.        , -0.70710678,  0.70710678,  0.        ,  0.        ]])

In [6]:
# follow figure in the textbook
U = np.array([[.14,0],
             [.42,0],
             [.56,0],
             [.70,0],
             [0,.60],
             [0,.75],
             [0,.30]
             ])

Sigma = np.array([[12.4,0],
                 [0,9.5]
                 ])

V_trans = np.array([[.58,.58,.58,0,0],
                    [0,0,0,.71,.71]])

V_trans

array([[0.58, 0.58, 0.58, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.71, 0.71]])

In [7]:
# multiply leslie's ratings with de-transposed V_trans matrix 
V = V_trans.transpose()

# concept space
CS = np.dot(Leslie,V)
CS

array([1.74, 2.84])

In [8]:
# What Leslie feels about the other movies
np.dot(CS,V_trans)

array([1.0092, 1.0092, 1.0092, 2.0164, 2.0164])

In [9]:
Leslie

array([0, 3, 0, 0, 4])

In [ ]:
# leslie like romance, chick flicks, rom-coms over other movies. 