Katie Briggs
Week 8 Exercises
DSC550-302

## 1. Dimensionality Reduction Part A

In [1]:
# import required libraries
import pandas as pd
import numpy as np
import scipy.linalg as la

In [2]:
#Create dataframe
m = {'M': [1,2,5], 
         'N': [2,3,5], 
         'P': [3,2,5], 
         'Q': [4,5,3], 
         'R': [5,3,2]}

movies = pd.DataFrame(m, index = ['A', 'B', 'C'])

#Preview dataframe
movies

M  N  P  Q  R
A  1  2  3  4  5
B  2  3  2  5  3
C  5  5  5  3  2

In [3]:
# find the mean for each row
movies.mean(axis = 1)

A    3.0
B    3.0
C    4.0
dtype: float64

In [4]:
# Minus mean of each row this is from each value in row
df = movies.sub(movies.mean(axis = 1), axis = 0)
df

M    N    P    Q    R
A -2.0 -1.0  0.0  1.0  2.0
B -1.0  0.0 -1.0  2.0  0.0
C  1.0  1.0  1.0 -1.0 -2.0

In [5]:
# find the mean for each column

df.mean()

M   -0.666667
N    0.000000
P    0.000000
Q    0.666667
R    0.000000
dtype: float64

In [6]:

# minus the mean of each column from each value in column
df = df.sub(df.mean(axis = 0), axis = 1)
df

M    N    P         Q    R
A -1.333333 -1.0  0.0  0.333333  2.0
B -0.333333  0.0 -1.0  1.333333  0.0
C  1.666667  1.0  1.0 -1.666667 -2.0

## Part B

In [7]:
# create an array for each row
a = np.array([1,0,1,0,1,2])
b = np.array([1,1,0,0,1,6])
c = np.array([0,1,0,1,0,2])

# create label for each row
rows = ['a','b', 'c']
labels = [a,b,c]

In [8]:
# cosine distance function that takes 2 inputs
def cosDist(x, y):
    return np.dot(x, y) / (np.sqrt(np.sum(np.power(x, 2))) * np.sqrt(np.sum(np.power(y, 2))))

# weighted cosine that takes x, y, attr_index, and alpha 
def weightcos(x, y, attr_index, alpha):
    a = np.copy(x)
    b = np.copy(y)
    
    if len(x) != len(y):
        print('Lengths do no match')
        return 0
    
    # assign weights to attributes
    a[attr_index] = a[attr_index] * alpha
    b[attr_index] = b[attr_index] * alpha
    
    # return cosDist with the weights
    return cosDist(a,b)

In [9]:
# weights
index = 5
weights = [0,0.5,1,2]

# print each angle cosine for each pair
for i, (r,l) in enumerate(zip(labels, rows)):
    for j in range(len(labels)):
        if i == j:
            next
        else:
            for w in weights:
                angle_cosine = weightcos(r, labels[j], index, w)
                print(f'{rows[i]} - {rows[j]} | {w:<3}: {round(angle_cosine,4)}')

a - b | 0  : 0.6667
a - b | 0.5: 0.7217
a - b | 1  : 0.8473
a - b | 2  : 0.9461
a - c | 0  : 0.0
a - c | 0.5: 0.2887
a - c | 1  : 0.6172
a - c | 2  : 0.8652
b - a | 0  : 0.6667
b - a | 0.5: 0.7217
b - a | 1  : 0.8473
b - a | 2  : 0.9461
b - c | 0  : 0.4082
b - c | 0.5: 0.6667
b - c | 1  : 0.8498
b - c | 2  : 0.9526
c - a | 0  : 0.0
c - a | 0.5: 0.2887
c - a | 1  : 0.6172
c - a | 2  : 0.8652
c - b | 0  : 0.4082
c - b | 0.5: 0.6667
c - b | 1  : 0.8498
c - b | 2  : 0.9526


## Part C

In [11]:

col1 = np.array([2/7, 3/7, 6/7])
col1

array([0.28571429, 0.42857143, 0.85714286])

## Part D

In [14]:
# create an array for the points
x = np.array([[1,1], [2,2], [3,4]])
y = np.dot(x.transpose(), x)

eigvals, eigvecs = la.eig(y)

print(eigvecs)

eigvals.real

[[-0.77512996 -0.63180182]
 [ 0.63180182 -0.77512996]]


array([ 0.14344504, 34.85655496])

## Part E

In [15]:
# create orthogonal vector
v = np.array([1,2,3])

u = np.array([1,1,-1])
np.dot(v,u)

0

## Part F

In [16]:
# dataframe from matrix M
M = pd.DataFrame(np.array([[1, 0, 0], [0, 2, 0], [0, 0, 0]]))

# Moore-Penrose pseudoinverse
np.linalg.pinv(M)

array([[1. , 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 0. ]])